const translations = {
  en: {
    nav:{studio:"Home",services:"Services",experiences:"Parties & Experiences",education:"Hub Academy",partnership:"The Hub Culture",upload:"Upload Files",client:"Client Login",contact:"Contact"},
    common:{book:"Book now",bookSession:"Book a session",viewPrices:"View prices",enquire:"Enquire",learnMore:"Explore service"},
    hero:{eyebrow:"Recording studio · Loulé, Algarve",title:"Your sound, made real.",copy:"Professional recording, production, mixing, voiceover and creative experiences inside The Hub Culture.",explore:"Explore the studio",meta1:"25+ years' experience",meta2:"Release-ready sound",meta3:"Prices include VAT"},
    remoteHome:{eyebrow:"Remote voiceover & directed sessions",title:"Studio in Loulé. Control room anywhere.",copy:"Record voice, dialogue and remote podcast sessions in broadcast quality while producers, agencies and directors listen and direct live from anywhere.",item1:"Live direction through SessionLink Pro",item2:"Professional booth, Neumann U87 and experienced engineer",item3:"Clean takes, organised files and delivery to specification",cta:"Explore remote sessions",badge:"Live direction · Worldwide delivery",clients:"Selected brands and productions"},
    partyHome:{eyebrow:"SoundBunker birthday parties",title:"Not just a party. Their studio moment.",lead:"A private three-hour celebration combining recording, photography, food and creativity — with finished music and photographs to keep.",videoLabel:"A real SoundBunker birthday party",recordTitle:"Record together",recordCopy:"One hour in the studio with an engineer. Party songs are professionally mixed and mastered.",photoTitle:"Professional photoshoot",photoCopy:"One hour of guided group photography with 15 edited images included.",foodTitle:"Food, drinks & celebration",foodCopy:"A private setup with food and drinks included, plus time for cake and celebrating.",createTitle:"Make it their own",createCopy:"Add slime, bracelets, face painting, popcorn or T-shirt design.",birthday:"Birthday party",upTo:"Up to 15 children · VAT included",slot:"Private 3-hour slot · around 2.5 hours of activities",times:"Choose 10:00–13:00 or 15:00–18:00",extra:"Additional children €20 each",deposit:"€100 deposit; remaining balance paid on the party day",extrasTitle:"Creative extras",oneStation:"One creative station",twoStations:"Two creative stations",tshirt:"Create a T-shirt",each:"each",otherTitle:"Hen & stag studio parties",from650:"From €650",otherCopy:"A private recording and photography experience for groups of ten or more. Tell us your group size and celebration style.",cta:"See full party details"},
    intro:{eyebrow:"Built for artists",title:"A serious studio without the attitude.",copy:"SoundBunker Algarve brings more than 25 years of recording, production, mixing and mastering experience to central Loulé. Come with a finished track, a rough idea or no experience at all. We will meet you where you are and help you make the work stronger.",prices:"View studio prices"},
    services:{eyebrow:"SoundBunker services",title:"Everything your project needs.",copy:"Record, produce, finish and present your work under one roof.",recording:{title:"Recording & engineering",copy:"Vocals, instruments and complete sessions with an experienced engineer."},production:{title:"Music production",copy:"From the first idea to a bespoke, release-ready record."},mix:{title:"Mixing & mastering",copy:"Detailed, powerful mixes and masters that translate everywhere."},voice:{title:"Remote voiceover",copy:"Broadcast-quality sessions for agencies, brands and talent worldwide."},photo:{title:"Photography",copy:"Portraits, branding, family sessions and content created in the studio."},podcast:{title:"Podcast production",copy:"Professional recording, editing and finishing, including work with Portugal Diaries Podcast."}},
    pricing:{eyebrow:"Clear studio pricing",title:"Choose the time you need.",vat:"All displayed prices include 23% VAT.",engineer:"Recording with engineer",best:"Most popular",hire:"Studio hire",noEngineer:"Without engineer",hours:"hours",day:"Full day",bookHire:"Book studio hire",depositTitle:"Secure your session with €100.",depositCopy:"The VAT-inclusive deposit is paid when booking and the remaining balance is due on the session day."},
    record:{eyebrow:"Create your own original record",title:"Your idea. Your sound. Your release.",copy:"Two focused three-hour sessions to create a bespoke instrumental, record and develop your vocals, then professionally mix and master the finished song.",item1:"Original bespoke production",item2:"Lead vocals, harmonies, layers and effects",item3:"Professional mix and master",item4:"Exclusive rights to release your song",standard:"Standard payment plan",vat:"VAT included",pay1:"Booking deposit",pay2:"Session one",pay3:"Session two",pay4:"On completion",upfront:"Pay upfront and save €50",cta:"Create your record"},
    experience:{eyebrow:"Studio experiences",title:"Step behind the mic.",copy:"Record up to five songs, enjoy a professional photoshoot and take home finished music and photographs.",solo:"Solo",duet:"Duet",family:"Family",one:"One person",two:"Two people",four:"Up to four people",parties:"Birthday, hen and stag parties",partyCopy:"Private group studio experiences for a minimum of ten guests.",birthday:"Birthday from",henstag:"Hen / stag from"},
    market:{eyebrow:"Saturday Market Day · 10:00–14:00",title:"Walk in. Have a go.",copy:"No booking and no big commitment. Drop in while you are visiting Loulé Market for a short recording, a quick photoshoot or both.",mic:"Mic Drop",photo:"Photo Pop-In",combo:"Mic + Pics",vat:"Solo · duet · family. VAT included."},
    education:{eyebrow:"Hub Academy · Creative education",title:"Learn it. Earn it. Wear it.",copy:"Practical workshops, one-to-one tuition and after-school clubs across music, art and street culture — with achievement patches that reward real skills and progression.",ages:"Ages 6–16 · 16:30–18:30",explore:"Explore. Discover. Develop.",d1:"Recording & vocals",d2:"Music production",d3:"Mixing & mastering",d4:"Photography",d5:"DJ skills",d6:"Design a T-shirt brand",d7:"Graffiti",d8:"Breakdancing",tue:"Tuesday",wed:"Wednesday",thu:"Thursday",age1:"Ages 6–9",age2:"Ages 10–12",age3:"Ages 13–16",form:"Download registration form",ask:"Ask about a place",trial:"Trial",single:"Single session",weekly:"Weekly",twice:"Twice weekly",term:"12 sessions",month:"/month",priceNote:"Two-hour sessions. VAT included. Creativity Starter Kit €35."},
    photo:{eyebrow:"Photography studio",title:"Professional images, your way.",mini:"Mini · 30 min · 5 images",signature:"Signature · 1 hour · 10 images",premium:"Premium · 90 min · 20 images",branding:"Business branding · 1 hour · 15 images",addons:"Add-ons include extra edits, complete galleries, social reels, behind-the-scenes video and additional studio time."},
    hub:{eyebrow:"SoundBunker × The Hub Culture",title:"One home for sound, art and movement.",copy:"SoundBunker is based inside The Hub Culture, an independent creative community in central Loulé. Together we connect recording, photography, graffiti, skating, dance and youth development in one welcoming space.",location:"Right beside Loulé Municipal Market."},
    reviews:{eyebrow:"Google reviews",title:"Hear it from the people who have recorded here.",copy:"Explore our latest verified reviews or share your SoundBunker experience.",cta:"View Google reviews"},
    booking:{eyebrow:"Online booking",title:"Book your studio time.",copy:"Choose your session, select an available date and secure it with your VAT-inclusive deposit.",rule1:"Weekdays: 10:00, 13:00 or 16:00",rule2:"Saturday: 16:00, two hours only",rule3:"Sunday: 10:00, two or four hours",rule4:"Free move with more than 24 hours' notice",policy:"The deposit is non-refundable for cancellation or changes within 24 hours."},
    form:{service:"Session",date:"Date",time:"Start time",chooseDate:"Choose a date first",name:"Full name",email:"Email",phone:"Phone",nif:"NIF / tax number",notes:"Session notes",terms:"I accept the booking and cancellation terms.",total:"Session total",due:"Due now",pay:"Continue to secure payment",loading:"Checking availability…",none:"No times are available for this date.",error:"Online payment is not connected yet. Please email bookings@soundbunker.pt and we will hold the selected time for you.",invalid:"Please complete all required fields."},
    contact:{eyebrow:"Visit SoundBunker",title:"In the heart of Loulé.",studio:"Home",directions:"Get directions",bookings:"Bookings",phone:"Telephone number coming soon.",follow:"Follow"}
  },
  pt: {
    nav:{studio:"Estúdio",services:"Serviços",experiences:"Festas & Experiências",education:"Hub Academy",partnership:"The Hub Culture",upload:"Enviar ficheiros",client:"Área do Cliente",contact:"Contacto"},
    common:{book:"Reservar",bookSession:"Reservar sessão",viewPrices:"Ver preços",enquire:"Pedir informações",learnMore:"Explorar serviço"},
    hero:{eyebrow:"Estúdio de gravação · Loulé, Algarve",title:"O seu som, tornado realidade.",copy:"Gravação profissional, produção, mistura, voz-off e experiências criativas dentro do The Hub Culture.",explore:"Conhecer o estúdio",meta1:"Mais de 25 anos de experiência",meta2:"Som pronto para lançamento",meta3:"Preços com IVA incluído"},
    remoteHome:{eyebrow:"Voz-off remota e sessões dirigidas",title:"Estúdio em Loulé. Sala de controlo mundial.",copy:"Grave voz, diálogo e sessões remotas de podcast com qualidade broadcast enquanto produtores, agências e realizadores ouvem e dirigem em direto a partir de qualquer lugar.",item1:"Direção em direto através do SessionLink Pro",item2:"Cabine profissional, Neumann U87 e técnico experiente",item3:"Tomadas limpas, ficheiros organizados e entrega segundo as especificações",cta:"Explorar sessões remotas",badge:"Direção em direto · Entrega mundial",clients:"Marcas e produções selecionadas"},
    partyHome:{eyebrow:"Festas de aniversário no SoundBunker",title:"Não é apenas uma festa. É o momento deles em estúdio.",lead:"Uma celebração privada de três horas com gravação, fotografia, comida e criatividade — com música finalizada e fotografias para guardar.",videoLabel:"Festa de aniversário real no SoundBunker",recordTitle:"Gravar em conjunto",recordCopy:"Uma hora no estúdio com técnico. As músicas da festa são misturadas e masterizadas profissionalmente.",photoTitle:"Sessão fotográfica profissional",photoCopy:"Uma hora de fotografia de grupo orientada com 15 imagens editadas incluídas.",foodTitle:"Comida, bebidas e celebração",foodCopy:"Configuração privada com comida e bebidas incluídas e tempo para o bolo e a festa.",createTitle:"Personalize a festa",createCopy:"Adicione slime, pulseiras, pintura facial, pipocas ou design de T-shirts.",birthday:"Festa de aniversário",upTo:"Até 15 crianças · IVA incluído",slot:"Slot privado de 3 horas · cerca de 2,5 horas de atividades",times:"Escolha 10:00–13:00 ou 15:00–18:00",extra:"Crianças adicionais €20 cada",deposit:"Sinal de €100; saldo restante pago no dia da festa",extrasTitle:"Extras criativos",oneStation:"Uma estação criativa",twoStations:"Duas estações criativas",tshirt:"Criar uma T-shirt",each:"cada",otherTitle:"Festas de despedida em estúdio",from650:"Desde €650",otherCopy:"Uma experiência privada de gravação e fotografia para grupos de dez ou mais pessoas. Diga-nos o tamanho do grupo e o tipo de celebração.",cta:"Ver todos os detalhes"},
    intro:{eyebrow:"Criado para artistas",title:"Um estúdio profissional, sem atitudes.",copy:"O SoundBunker Algarve traz mais de 25 anos de experiência em gravação, produção, mistura e masterização para o centro de Loulé. Venha com uma faixa acabada, uma ideia inicial ou sem qualquer experiência. Trabalhamos consigo a partir do ponto em que está para tornar o projeto mais forte.",prices:"Ver preços do estúdio"},
    services:{eyebrow:"Serviços SoundBunker",title:"Tudo o que o seu projeto precisa.",copy:"Grave, produza, finalize e apresente o seu trabalho num só espaço.",recording:{title:"Gravação e engenharia",copy:"Vozes, instrumentos e sessões completas com um técnico experiente."},production:{title:"Produção musical",copy:"Da primeira ideia a uma música original pronta para lançamento."},mix:{title:"Mistura e masterização",copy:"Misturas detalhadas e potentes e masters que funcionam em qualquer sistema."},voice:{title:"Voz-off remota",copy:"Sessões com qualidade broadcast para agências, marcas e talentos em qualquer lugar."},photo:{title:"Fotografia",copy:"Retratos, branding, sessões de família e conteúdos criados em estúdio."},podcast:{title:"Produção de podcasts",copy:"Gravação, edição e finalização profissional, incluindo trabalho com o Portugal Diaries Podcast."}},
    pricing:{eyebrow:"Preços simples",title:"Escolha o tempo de que precisa.",vat:"Todos os preços apresentados incluem IVA a 23%.",engineer:"Gravação com técnico",best:"Mais popular",hire:"Aluguer de estúdio",noEngineer:"Sem técnico",hours:"horas",day:"Dia completo",bookHire:"Reservar estúdio",depositTitle:"Garanta a sessão com €100.",depositCopy:"O sinal inclui IVA, é pago na reserva e o saldo restante vence no dia da sessão."},
    record:{eyebrow:"Crie a sua própria música original",title:"A sua ideia. O seu som. O seu lançamento.",copy:"Duas sessões focadas de três horas para criar um instrumental à medida, gravar e desenvolver as vozes e depois misturar e masterizar profissionalmente a música final.",item1:"Produção original à medida",item2:"Voz principal, harmonias, camadas e efeitos",item3:"Mistura e masterização profissionais",item4:"Direitos exclusivos para lançar a música",standard:"Plano de pagamento normal",vat:"IVA incluído",pay1:"Sinal da reserva",pay2:"Primeira sessão",pay3:"Segunda sessão",pay4:"Na conclusão",upfront:"Pague antecipadamente e poupe €50",cta:"Criar a sua música"},
    experience:{eyebrow:"Experiências em estúdio",title:"Entre no estúdio.",copy:"Grave até cinco músicas, faça uma sessão fotográfica profissional e leve música e fotografias finalizadas.",solo:"Solo",duet:"Dueto",family:"Família",one:"Uma pessoa",two:"Duas pessoas",four:"Até quatro pessoas",parties:"Festas de aniversário, despedidas de solteira e de solteiro",partyCopy:"Experiências privadas em estúdio para grupos com um mínimo de dez pessoas.",birthday:"Aniversário desde",henstag:"Despedida desde"},
    market:{eyebrow:"Market Day aos sábados · 10:00–14:00",title:"Entre e experimente.",copy:"Sem reserva nem compromisso. Passe por cá enquanto visita o Mercado de Loulé para uma gravação curta, uma sessão fotográfica rápida ou as duas.",mic:"Mic Drop",photo:"Photo Pop-In",combo:"Mic + Fotos",vat:"Solo · dueto · família. IVA incluído."},
    education:{eyebrow:"Hub Academy · Educação criativa",title:"Aprender. Conquistar. Usar.",copy:"Um clube bilingue em inglês e português onde os jovens fazem amigos, exploram disciplinas criativas e desenvolvem as competências com que mais se identificam.",ages:"Dos 6 aos 16 anos · 16:30–18:30",explore:"Explorar. Descobrir. Desenvolver.",d1:"Gravação e voz",d2:"Produção musical",d3:"Mistura e masterização",d4:"Fotografia",d5:"DJ",d6:"Criar uma marca de T-shirts",d7:"Graffiti",d8:"Breakdance",tue:"Terça-feira",wed:"Quarta-feira",thu:"Quinta-feira",age1:"6–9 anos",age2:"10–12 anos",age3:"13–16 anos",form:"Descarregar ficha de inscrição",ask:"Perguntar sobre vagas",trial:"Aula experimental",single:"Sessão avulsa",weekly:"Semanal",twice:"Duas vezes por semana",term:"12 sessões",month:"/mês",priceNote:"Sessões de duas horas. IVA incluído. Kit Criativo Inicial €35."},
    photo:{eyebrow:"Estúdio fotográfico",title:"Imagens profissionais à sua maneira.",mini:"Mini · 30 min · 5 imagens",signature:"Signature · 1 hora · 10 imagens",premium:"Premium · 90 min · 20 imagens",branding:"Branding empresarial · 1 hora · 15 imagens",addons:"Extras disponíveis: mais edições, galeria completa, reels, vídeo de bastidores e tempo adicional de estúdio."},
    hub:{eyebrow:"SoundBunker × The Hub Culture",title:"Uma casa para som, arte e movimento.",copy:"O SoundBunker está dentro do The Hub Culture, uma comunidade criativa independente no centro de Loulé. Em conjunto, ligamos gravação, fotografia, graffiti, skate, dança e desenvolvimento juvenil num espaço acolhedor.",location:"Mesmo ao lado do Mercado Municipal de Loulé."},
    reviews:{eyebrow:"Avaliações Google",title:"A opinião de quem já gravou connosco.",copy:"Veja as avaliações verificadas mais recentes ou partilhe a sua experiência SoundBunker.",cta:"Ver avaliações Google"},
    booking:{eyebrow:"Reservas online",title:"Reserve tempo de estúdio.",copy:"Escolha a sessão, selecione uma data disponível e garanta-a com o sinal, já com IVA incluído.",rule1:"Dias úteis: 10:00, 13:00 ou 16:00",rule2:"Sábado: 16:00, apenas duas horas",rule3:"Domingo: 10:00, duas ou quatro horas",rule4:"Alteração gratuita com mais de 24 horas de antecedência",policy:"O sinal não é reembolsável em cancelamentos ou alterações com menos de 24 horas."},
    form:{service:"Sessão",date:"Data",time:"Hora de início",chooseDate:"Escolha primeiro uma data",name:"Nome completo",email:"Email",phone:"Telefone",nif:"NIF",notes:"Notas sobre a sessão",terms:"Aceito os termos de reserva e cancelamento.",total:"Total da sessão",due:"A pagar agora",pay:"Continuar para pagamento seguro",loading:"A verificar disponibilidade…",none:"Não existem horários disponíveis nesta data.",error:"O pagamento online ainda não está ligado. Envie um email para bookings@soundbunker.pt e guardaremos o horário selecionado.",invalid:"Preencha todos os campos obrigatórios."},
    contact:{eyebrow:"Visite o SoundBunker",title:"No coração de Loulé.",studio:"Estúdio",directions:"Obter direções",bookings:"Reservas",phone:"Número de telefone disponível em breve.",follow:"Siga-nos"}
  },
  de: {
    nav:{studio:"Home",services:"Services",experiences:"Partys & Erlebnisse",education:"Hub Academy",partnership:"The Hub Culture",upload:"Dateien hochladen",client:"Kunden-Login",contact:"Kontakt"},
    common:{book:"Jetzt buchen",bookSession:"Session buchen",viewPrices:"Preise ansehen",enquire:"Anfragen",learnMore:"Service ansehen"},
    hero:{eyebrow:"Tonstudio · Loulé, Algarve",title:"Dein Sound. Echt gemacht.",copy:"Professionelle Aufnahmen, Produktion, Mixing, Voiceover und kreative Erlebnisse in The Hub Culture.",explore:"Studio entdecken",meta1:"25+ Jahre Erfahrung",meta2:"Release-fertiger Sound",meta3:"Preise inkl. MwSt."},
    remoteHome:{eyebrow:"Remote Voiceover & Regie-Sessions",title:"Studio in Loulé. Regie überall.",copy:"Sprach-, Dialog- und Podcast-Aufnahmen in Broadcast-Qualität mit Live-Regie von überall.",item1:"Live-Regie über SessionLink Pro",item2:"Professionelle Kabine, Neumann U87 und erfahrener Engineer",item3:"Saubere Takes, organisierte Dateien und Lieferung nach Vorgabe",cta:"Remote Sessions ansehen",badge:"Live-Regie · Weltweite Lieferung",clients:"Ausgewählte Marken und Produktionen"},
    partyHome:{eyebrow:"SoundBunker Geburtstagspartys",title:"Nicht nur eine Party. Ihr Studio-Moment.",lead:"Drei Stunden privat: Aufnahme, Fotos, Essen und Kreativität – inklusive fertiger Musik und Bilder.",videoLabel:"Eine echte SoundBunker Geburtstagsparty",recordTitle:"Gemeinsam aufnehmen",recordCopy:"Eine Stunde im Studio mit Engineer. Die Songs werden professionell gemischt und gemastert.",photoTitle:"Professionelles Fotoshooting",photoCopy:"Eine Stunde geführtes Gruppenshooting mit 15 bearbeiteten Bildern.",foodTitle:"Essen, Getränke & Feiern",foodCopy:"Privater Bereich mit Essen und Getränken sowie Zeit für Kuchen und Feiern.",createTitle:"Individuell gestalten",createCopy:"Optional Schleim, Armbänder, Face Paint, Popcorn oder T-Shirt-Design.",birthday:"Geburtstagsparty",upTo:"Bis 15 Kinder · MwSt. inklusive",slot:"Privater 3-Stunden-Slot · ca. 2,5 Stunden Aktivitäten",times:"10:00–13:00 oder 15:00–18:00",extra:"Zusätzliche Kinder je 20 €",deposit:"100 € Anzahlung; Restbetrag am Partytag",extrasTitle:"Kreative Extras",oneStation:"Eine Kreativstation",twoStations:"Zwei Kreativstationen",tshirt:"T-Shirt gestalten",each:"pro Person",otherTitle:"Junggesellen-/Junggesellinnen-Partys",from650:"Ab 650 €",otherCopy:"Privates Aufnahme- und Fotoerlebnis für Gruppen ab zehn Personen.",cta:"Alle Party-Details"},
    intro:{eyebrow:"Für Künstler gemacht",title:"Ein professionelles Studio ohne Attitüde.",copy:"SoundBunker Algarve bringt mehr als 25 Jahre Erfahrung in Aufnahme, Produktion, Mixing und Mastering ins Zentrum von Loulé.",prices:"Studiopreise ansehen"},
    services:{eyebrow:"SoundBunker Services",title:"Alles für dein Projekt.",copy:"Aufnehmen, produzieren, fertigstellen und präsentieren – unter einem Dach.",recording:{title:"Recording & Engineering",copy:"Vocals, Instrumente und komplette Sessions mit erfahrenem Engineer."},production:{title:"Musikproduktion",copy:"Von der ersten Idee bis zum individuellen, release-fertigen Track."},mix:{title:"Mixing & Mastering",copy:"Detaillierte, kraftvolle Mixe und Masters, die überall funktionieren."},voice:{title:"Remote Voiceover",copy:"Broadcast-Qualität für Agenturen, Marken und Talents weltweit."},photo:{title:"Fotografie",copy:"Porträts, Branding, Familien-Sessions und Studio-Content."},podcast:{title:"Podcast-Produktion",copy:"Professionelle Aufnahme, Bearbeitung und Fertigstellung."}},
    pricing:{eyebrow:"Klare Studiopreise",title:"Wähle die Zeit, die du brauchst.",vat:"Alle angezeigten Preise enthalten 23 % MwSt.",engineer:"Aufnahme mit Engineer",best:"Beliebt",hire:"Studio mieten",noEngineer:"Ohne Engineer",hours:"Stunden",day:"Ganzer Tag",bookHire:"Studio buchen",depositTitle:"Session mit Anzahlung sichern.",depositCopy:"Die angezeigte Anzahlung ist bei Buchung fällig; der Restbetrag am Session-Tag."},
    record:{eyebrow:"Erstelle deinen eigenen Original-Track",title:"Deine Idee. Dein Sound. Dein Release.",copy:"Zwei fokussierte 3-Stunden-Sessions für Instrumental, Vocals, Produktion, Mix und Master.",item1:"Individuelle Originalproduktion",item2:"Lead-Vocals, Harmonien, Layer und Effekte",item3:"Professioneller Mix und Master",item4:"Exklusive Rechte zur Veröffentlichung",standard:"Standard-Zahlungsplan",vat:"MwSt. inklusive",pay1:"Buchungsanzahlung",pay2:"Session eins",pay3:"Session zwei",pay4:"Bei Fertigstellung",upfront:"450 € komplett zahlen und 50 € sparen",cta:"Track erstellen"},
    experience:{eyebrow:"Studio-Erlebnisse",title:"Ans Mikrofon.",copy:"Bis zu fünf Songs aufnehmen, professionelles Fotoshooting und fertige Musik und Bilder mitnehmen.",solo:"Solo",duet:"Duo",family:"Familie",one:"Eine Person",two:"Zwei Personen",four:"Bis vier Personen",parties:"Geburtstags-, Hen- und Stag-Partys",partyCopy:"Private Studio-Erlebnisse für Gruppen.",birthday:"Geburtstag ab",henstag:"Hen / Stag ab"},
    market:{eyebrow:"Market Day Samstag · 10:00–14:00",title:"Reinkommen und ausprobieren.",copy:"Keine Buchung nötig. Kurze Aufnahme, Fotoshooting oder beides während deines Besuchs am Markt in Loulé.",mic:"Mic Drop",photo:"Photo Pop-In",combo:"Mic + Fotos",vat:"Solo · Duo · Familie. MwSt. inklusive."},
    education:{eyebrow:"Hub Academy",title:"Lernen. Verdienen. Tragen.",copy:"Workshops, Einzelunterricht und After-School-Clubs für Musik, Kunst, Skaten, Graffiti, Tanz und Fotografie.",ages:"6–16 Jahre · 16:30–18:30",explore:"Entdecken. Lernen. Entwickeln.",d1:"Recording & Gesang",d2:"Musikproduktion",d3:"Mixing & Mastering",d4:"Fotografie",d5:"DJ",d6:"T-Shirt-Marke gestalten",d7:"Graffiti",d8:"Breakdance",tue:"Dienstag",wed:"Mittwoch",thu:"Donnerstag",age1:"6–9 Jahre",age2:"10–12 Jahre",age3:"13–16 Jahre",form:"Anmeldeformular herunterladen",ask:"Platz anfragen",trial:"Probestunde",single:"Einzelsession",weekly:"Wöchentlich",twice:"Zweimal wöchentlich",term:"12 Sessions",month:"/Monat",priceNote:"Zweistündige Sessions. MwSt. inklusive. Starter-Kit 35 €."},
    photo:{eyebrow:"Studiofotografie",title:"Professionelle Bilder, auf deine Art.",mini:"Mini · 30 Min · 5 Bilder",signature:"Signature · 1 Std · 10 Bilder",premium:"Premium · 90 Min · 20 Bilder",branding:"Business Branding · 1 Std · 15 Bilder",addons:"Extras: zusätzliche Retusche, komplette Galerie, Reels, Behind-the-Scenes-Video und zusätzliche Studiozeit."},
    hub:{eyebrow:"SoundBunker × The Hub Culture",title:"Ein Zuhause für Sound, Kunst und Bewegung.",copy:"SoundBunker befindet sich in The Hub Culture im Zentrum von Loulé – Recording, Fotografie, Graffiti, Skate, Tanz und Jugendförderung an einem Ort.",location:"Direkt neben dem Mercado Municipal de Loulé."},
    reviews:{eyebrow:"Google Bewertungen",title:"Hör von Menschen, die schon hier aufgenommen haben.",copy:"Lies aktuelle Bewertungen oder teile deine SoundBunker-Erfahrung.",cta:"Google Bewertungen ansehen"},
    booking:{eyebrow:"Online-Buchung",title:"Studiozeit reservieren.",copy:"Wähle deine Session, Datum und Uhrzeit. Zahlungs- und Kalenderintegration wird als nächster Schritt verbunden.",rule1:"Wochentags: 10:00, 13:00 oder 16:00",rule2:"Samstag: 16:00, nur 2 Stunden",rule3:"Sonntag: 10:00, 2 oder 4 Stunden",rule4:"Kostenlose Umbuchung mit mehr als 24 Stunden Vorlauf",policy:"Anzahlungen sind bei Stornierung oder Änderung innerhalb von 24 Stunden nicht erstattungsfähig."},
    form:{service:"Session",date:"Datum",time:"Startzeit",chooseDate:"Zuerst Datum wählen",name:"Vollständiger Name",email:"E-Mail",phone:"Telefon",nif:"NIF / Steuernummer",notes:"Hinweise zur Session",terms:"Ich akzeptiere die Buchungs- und Stornobedingungen.",total:"Gesamtpreis",due:"Jetzt fällig",pay:"Buchungsanfrage senden",loading:"Verfügbarkeit wird geprüft…",none:"Für dieses Datum sind keine Zeiten verfügbar.",error:"Online-Zahlung wird gerade eingerichtet. Bitte schreibe an bookings@soundbunker.pt und wir halten deinen gewählten Termin fest.",invalid:"Bitte alle Pflichtfelder ausfüllen."},
    contact:{eyebrow:"SoundBunker besuchen",title:"Im Herzen von Loulé.",studio:"Home",directions:"Route",bookings:"Buchungen",phone:"Telefonnummer folgt in Kürze.",follow:"Folgen"}
  },
  fr: {
    nav:{studio:"Home",services:"Services",experiences:"Fêtes & Expériences",education:"Hub Academy",partnership:"The Hub Culture",upload:"Upload Files",client:"Espace client",contact:"Contact"},
    common:{book:"Réserver",bookSession:"Réserver une session",viewPrices:"Voir les tarifs",enquire:"Nous contacter",learnMore:"Découvrir le service"},
    hero:{eyebrow:"Studio d'enregistrement · Loulé, Algarve",title:"Votre son prend vie.",copy:"Enregistrement professionnel, production, mixage, voix off et expériences créatives au sein de The Hub Culture.",explore:"Découvrir le studio",meta1:"Plus de 25 ans d'expérience",meta2:"Son prêt à sortir",meta3:"Prix TVA comprise"},
    remoteHome:{eyebrow:"Voix off à distance & sessions dirigées",title:"Studio à Loulé. Régie dans le monde entier.",copy:"Enregistrez voix, dialogue et podcasts à distance en qualité broadcast pendant que producteurs, agences et réalisateurs écoutent et dirigent en direct, où qu’ils soient.",item1:"Direction en direct via SessionLink Pro",item2:"Cabine professionnelle, Neumann U87 et ingénieur expérimenté",item3:"Prises propres, fichiers organisés et livraison conforme",cta:"Découvrir les sessions à distance",badge:"Direction en direct · Livraison mondiale",clients:"Marques et productions sélectionnées"},
    partyHome:{eyebrow:"Anniversaires chez SoundBunker",title:"Bien plus qu’une fête. Leur moment en studio.",lead:"Une célébration privée de trois heures réunissant enregistrement, photographie, goûter et créativité — avec musique finalisée et photos à conserver.",videoLabel:"Un véritable anniversaire SoundBunker",recordTitle:"Enregistrer ensemble",recordCopy:"Une heure en studio avec un ingénieur. Les chansons sont mixées et masterisées professionnellement.",photoTitle:"Séance photo professionnelle",photoCopy:"Une heure de photographie de groupe guidée avec 15 images retouchées incluses.",foodTitle:"Goûter, boissons et fête",foodCopy:"Installation privée avec nourriture et boissons incluses, plus un moment pour le gâteau.",createTitle:"Une fête personnalisée",createCopy:"Ajoutez slime, bracelets, maquillage, popcorn ou création de T-shirts.",birthday:"Fête d’anniversaire",upTo:"Jusqu’à 15 enfants · TVA comprise",slot:"Créneau privé de 3 heures · environ 2 h 30 d’activités",times:"Choisissez 10:00–13:00 ou 15:00–18:00",extra:"Enfant supplémentaire 20 €",deposit:"Acompte de 100 €; solde payé le jour de la fête",extrasTitle:"Options créatives",oneStation:"Un atelier créatif",twoStations:"Deux ateliers créatifs",tshirt:"Créer un T-shirt",each:"chacun",otherTitle:"EVJF & EVG en studio",from650:"À partir de 650 €",otherCopy:"Une expérience privée d’enregistrement et de photographie pour dix personnes ou plus. Indiquez-nous la taille du groupe et le style de fête.",cta:"Voir tous les détails"},
    intro:{eyebrow:"Conçu pour les artistes",title:"Un studio sérieux, sans prétention.",copy:"SoundBunker Algarve apporte plus de 25 ans d'expérience en enregistrement, production, mixage et mastering au centre de Loulé. Venez avec un morceau terminé, une première idée ou sans aucune expérience. Nous partons de votre niveau pour renforcer votre projet.",prices:"Voir les tarifs du studio"},
    services:{eyebrow:"Services SoundBunker",title:"Tout ce dont votre projet a besoin.",copy:"Enregistrez, produisez, finalisez et présentez votre travail sous un même toit.",recording:{title:"Enregistrement & ingénierie",copy:"Voix, instruments et sessions complètes avec un ingénieur expérimenté."},production:{title:"Production musicale",copy:"De la première idée à un titre original prêt à sortir."},mix:{title:"Mixage & mastering",copy:"Des mixages précis et puissants et des masters qui fonctionnent partout."},voice:{title:"Voix off à distance",copy:"Sessions de qualité broadcast pour les agences, marques et talents du monde entier."},photo:{title:"Photographie",copy:"Portraits, image de marque, familles et contenu créés en studio."},podcast:{title:"Production de podcasts",copy:"Enregistrement, montage et finition professionnels, avec notamment Portugal Diaries Podcast."}},
    pricing:{eyebrow:"Tarifs simples",title:"Choisissez le temps nécessaire.",vat:"Tous les prix affichés incluent 23 % de TVA.",engineer:"Enregistrement avec ingénieur",best:"Le plus populaire",hire:"Location du studio",noEngineer:"Sans ingénieur",hours:"heures",day:"Journée complète",bookHire:"Réserver le studio",depositTitle:"Réservez votre session avec 100 €.",depositCopy:"L'acompte, TVA comprise, est payé à la réservation. Le solde est dû le jour de la session."},
    record:{eyebrow:"Créez votre propre titre original",title:"Votre idée. Votre son. Votre sortie.",copy:"Deux sessions ciblées de trois heures pour créer un instrumental sur mesure, enregistrer et développer les voix, puis mixer et masteriser professionnellement le titre final.",item1:"Production originale sur mesure",item2:"Voix principale, harmonies, couches et effets",item3:"Mixage et mastering professionnels",item4:"Droits exclusifs pour sortir votre titre",standard:"Paiement standard",vat:"TVA comprise",pay1:"Acompte de réservation",pay2:"Première session",pay3:"Deuxième session",pay4:"À la fin",upfront:"Payez d'avance et économisez 50 €",cta:"Créer votre titre"},
    experience:{eyebrow:"Expériences studio",title:"Passez derrière le micro.",copy:"Enregistrez jusqu'à cinq chansons, profitez d'une séance photo professionnelle et repartez avec votre musique et vos photos finalisées.",solo:"Solo",duet:"Duo",family:"Famille",one:"Une personne",two:"Deux personnes",four:"Jusqu'à quatre personnes",parties:"Anniversaires, EVJF et EVG",partyCopy:"Expériences privées en studio pour des groupes de dix personnes minimum.",birthday:"Anniversaire dès",henstag:"EVJF / EVG dès"},
    market:{eyebrow:"Market Day le samedi · 10:00–14:00",title:"Entrez et essayez.",copy:"Sans réservation ni gros engagement. Passez pendant votre visite du marché de Loulé pour un court enregistrement, une séance photo rapide ou les deux.",mic:"Mic Drop",photo:"Photo Pop-In",combo:"Mic + Photos",vat:"Solo · duo · famille. TVA comprise."},
    education:{eyebrow:"Éducation & enrichissement",title:"Club Créatif Après l'École",copy:"Un club bilingue anglais-portugais où les jeunes se font des amis, explorent des disciplines créatives et développent les compétences qui leur correspondent le mieux.",ages:"De 6 à 16 ans · 16:30–18:30",explore:"Explorer. Découvrir. Développer.",d1:"Enregistrement & chant",d2:"Production musicale",d3:"Mixage & mastering",d4:"Photographie",d5:"DJ",d6:"Créer une marque de T-shirts",d7:"Graffiti",d8:"Breakdance",tue:"Mardi",wed:"Mercredi",thu:"Jeudi",age1:"6–9 ans",age2:"10–12 ans",age3:"13–16 ans",form:"Télécharger le formulaire",ask:"Demander une place",trial:"Essai",single:"Session unique",weekly:"Chaque semaine",twice:"Deux fois par semaine",term:"12 sessions",month:"/mois",priceNote:"Sessions de deux heures. TVA comprise. Kit Créatif de Départ 35 €."},
    photo:{eyebrow:"Studio photo",title:"Des images professionnelles à votre façon.",mini:"Mini · 30 min · 5 images",signature:"Signature · 1 heure · 10 images",premium:"Premium · 90 min · 20 images",branding:"Image de marque · 1 heure · 15 images",addons:"Options : retouches supplémentaires, galerie complète, reels, vidéo en coulisses et temps de studio supplémentaire."},
    hub:{eyebrow:"SoundBunker × The Hub Culture",title:"Un lieu pour le son, l'art et le mouvement.",copy:"SoundBunker se trouve au sein de The Hub Culture, une communauté créative indépendante au centre de Loulé. Ensemble, nous réunissons enregistrement, photographie, graffiti, skate, danse et développement des jeunes dans un espace accueillant.",location:"Juste à côté du marché municipal de Loulé."},
    reviews:{eyebrow:"Avis Google",title:"Écoutez ceux qui ont déjà enregistré ici.",copy:"Consultez nos derniers avis vérifiés ou partagez votre expérience SoundBunker.",cta:"Voir les avis Google"},
    booking:{eyebrow:"Réservation en ligne",title:"Réservez votre studio.",copy:"Choisissez votre session, sélectionnez une date disponible et confirmez avec votre acompte TVA comprise.",rule1:"En semaine : 10:00, 13:00 ou 16:00",rule2:"Samedi : 16:00, deux heures uniquement",rule3:"Dimanche : 10:00, deux ou quatre heures",rule4:"Déplacement gratuit avec plus de 24 heures de préavis",policy:"L'acompte n'est pas remboursable en cas d'annulation ou de modification dans les 24 heures."},
    form:{service:"Session",date:"Date",time:"Heure de début",chooseDate:"Choisissez d'abord une date",name:"Nom complet",email:"E-mail",phone:"Téléphone",nif:"NIF / numéro fiscal",notes:"Notes sur la session",terms:"J'accepte les conditions de réservation et d'annulation.",total:"Total de la session",due:"À payer maintenant",pay:"Continuer vers le paiement sécurisé",loading:"Vérification des disponibilités…",none:"Aucun horaire n'est disponible à cette date.",error:"Le paiement en ligne n'est pas encore connecté. Écrivez à bookings@soundbunker.pt et nous garderons l'horaire choisi.",invalid:"Veuillez remplir tous les champs obligatoires."},
    contact:{eyebrow:"Visiter SoundBunker",title:"Au cœur de Loulé.",studio:"Home",directions:"Itinéraire",bookings:"Réservations",phone:"Numéro de téléphone bientôt disponible.",follow:"Suivre"}
  }
};

const sessions = [
  {id:"recording-2h",group:"recording",price:250,deposit:100,hours:2,names:{en:"Recording with engineer · 2 hours",pt:"Gravação com técnico · 2 horas",fr:"Enregistrement avec ingénieur · 2 heures",de:"Aufnahme mit Engineer · 2 Stunden"}},
  {id:"recording-4h",group:"recording",price:450,deposit:100,hours:4,names:{en:"Recording with engineer · 4 hours",pt:"Gravação com técnico · 4 horas",fr:"Enregistrement avec ingénieur · 4 heures",de:"Aufnahme mit Engineer · 4 Stunden"}},
  {id:"recording-day",group:"recording",price:675,deposit:100,hours:7,fullDay:true,names:{en:"Recording with engineer · Full day",pt:"Gravação com técnico · Dia completo",fr:"Enregistrement avec ingénieur · Journée complète",de:"Aufnahme mit Engineer · Ganzer Tag"}},
  {id:"hire-2h",group:"recording",price:100,deposit:50,hours:2,names:{en:"Solo studio hire · 2 hours",pt:"Aluguer solo · 2 horas",fr:"Location solo · 2 heures",de:"Studio ohne Engineer · 2 Stunden"}},
  {id:"hire-4h",group:"recording",price:175,deposit:75,hours:4,names:{en:"Solo studio hire · 4 hours",pt:"Aluguer solo · 4 horas",fr:"Location solo · 4 heures",de:"Studio ohne Engineer · 4 Stunden"}},
  {id:"hire-day",group:"recording",price:275,deposit:100,hours:7,fullDay:true,names:{en:"Solo studio hire · Full day",pt:"Aluguer solo · Dia completo",fr:"Location solo · Journée",de:"Studio ohne Engineer · Ganzer Tag"}},
  {id:"production",group:"production",price:500,deposit:100,hours:3,names:{en:"Original-song production · €500 payment plan",pt:"Produção original · plano de pagamento €500",fr:"Production originale · paiement échelonné 500 €",de:"Original-Song-Produktion · €500 Zahlungsplan"}},
  {id:"production-upfront",group:"production",price:450,deposit:450,hours:3,fullPayment:true,names:{en:"Original-song production · €450 one-off upfront deal",pt:"Produção original · oferta única €450 paga na totalidade",fr:"Production originale · offre unique 450 € payée intégralement",de:"Original-Song-Produktion · €450 Einmalzahlung"}},
  {id:"remote-1h",group:"voiceover",price:175,deposit:75,hours:1,names:{en:"Remote session · 1 hour",pt:"Sessão remota · 1 hora",fr:"Session à distance · 1 heure",de:"Remote Session · 1 Stunde"}},
  {id:"remote-half",group:"voiceover",price:600,deposit:150,hours:4,halfDay:true,names:{en:"Remote session · Half day",pt:"Sessão remota · Meio dia",fr:"Session à distance · Demi-journée",de:"Remote Session · Halber Tag"}},
  {id:"remote-day",group:"voiceover",price:1000,deposit:250,hours:7,fullDay:true,names:{en:"Remote session · Full day",pt:"Sessão remota · Dia completo",fr:"Session à distance · Journée",de:"Remote Session · Ganzer Tag"}},
  {id:"photo-mini",group:"photography",price:120,deposit:50,hours:.5,names:{en:"Photography Mini · 30 min",pt:"Fotografia Mini · 30 min",fr:"Photo Mini · 30 min",de:"Fotografie Mini · 30 Min"}},
  {id:"photo-signature",group:"photography",price:220,deposit:75,hours:1,names:{en:"Photography Signature · 1 hour",pt:"Fotografia Signature · 1 hora",fr:"Photo Signature · 1 heure",de:"Fotografie Signature · 1 Stunde"}},
  {id:"photo-premium",group:"photography",price:310,deposit:100,hours:1.5,names:{en:"Photography Premium · 90 min",pt:"Fotografia Premium · 90 min",fr:"Photo Premium · 90 min",de:"Fotografie Premium · 90 Min"}},
  {id:"photo-branding",group:"photography",price:280,deposit:100,hours:1,names:{en:"Business branding · 1 hour",pt:"Branding empresarial · 1 hora",fr:"Branding entreprise · 1 heure",de:"Business Branding · 1 Stunde"}},
  {id:"party-birthday",group:"parties",price:550,deposit:100,hours:3,partySlots:true,names:{en:"Birthday party · up to 15 children",pt:"Aniversário · até 15 crianças",fr:"Anniversaire · jusqu’à 15 enfants",de:"Geburtstagsparty · bis 15 Kinder"}},
  {id:"party-henstag",group:"parties",price:650,deposit:100,hours:3,partySlots:true,names:{en:"Hen / stag studio party · from",pt:"Despedida no estúdio · desde",fr:"EVJF / EVG au studio · dès",de:"Hen / Stag Studio-Party · ab"}},
  {id:"mix-12",group:"mixing",price:125,deposit:125,noSlot:true,fullPayment:true,names:{en:"Mixing · up to 12 channels",pt:"Mistura · até 12 canais",fr:"Mixage · jusqu’à 12 pistes",de:"Mixing · bis 12 Kanäle"}},
  {id:"mix-24",group:"mixing",price:185,deposit:185,noSlot:true,fullPayment:true,names:{en:"Mixing · up to 24 channels",pt:"Mistura · até 24 canais",fr:"Mixage · jusqu’à 24 pistes",de:"Mixing · bis 24 Kanäle"}},
  {id:"mix-48",group:"mixing",price:270,deposit:270,noSlot:true,fullPayment:true,names:{en:"Mixing · up to 48 channels",pt:"Mistura · até 48 canais",fr:"Mixage · jusqu’à 48 pistes",de:"Mixing · bis 48 Kanäle"}},
  {id:"master",group:"mixing",price:75,deposit:75,noSlot:true,fullPayment:true,names:{en:"Mastering",pt:"Masterização",fr:"Mastering",de:"Mastering"}},
  {id:"mixmaster-12",group:"mixing",price:185,deposit:185,noSlot:true,fullPayment:true,names:{en:"Mix + master · up to 12 channels",pt:"Mistura + master · até 12 canais",fr:"Mix + master · jusqu’à 12 pistes",de:"Mix + Master · bis 12 Kanäle"}},
  {id:"mixmaster-24",group:"mixing",price:245,deposit:245,noSlot:true,fullPayment:true,names:{en:"Mix + master · up to 24 channels",pt:"Mistura + master · até 24 canais",fr:"Mix + master · jusqu’à 24 pistes",de:"Mix + Master · bis 24 Kanäle"}},
  {id:"mixmaster-48",group:"mixing",price:335,deposit:335,noSlot:true,fullPayment:true,names:{en:"Mix + master · up to 48 channels",pt:"Mistura + master · até 48 canais",fr:"Mix + master · jusqu’à 48 pistes",de:"Mix + Master · bis 48 Kanäle"}}
];

const academyHomeTranslations = {
  en: {eyebrow:"THE HUB ACADEMY · CENTRAL LOULÉ",title:"Find your thing. Make it real.",copy:"A working studio and creative home for young people. Make music, art and media. Learn to skate and dance. Build skills with real practitioners, then wear your progress with pride.",cta:"Explore the Academy ↗",club1Label:"01 / MUSIC & AUDIO",club1Title:"Find your sound.",club1Copy:"Write it, perform it, record it. Leave with something that is yours.",club2Label:"02 / ART & MEDIA",club2Title:"Make something to be proud of.",club2Copy:"Shoot, paint, design and show your work beyond the classroom.",club3Label:"03 / MOVEMENT",club3Title:"Move, land it, own it.",club3Copy:"Find your balance on a board and your rhythm on the floor.",footTitle:"EARN IT. WEAR IT.",footCopy:"Discover → Develop → Achieve → Lead. Collect patches as your skills grow.",footLink:"See the patch system ↗"},
  pt: {eyebrow:"THE HUB ACADEMY · CENTRO DE LOULÉ",title:"Descobre o teu talento. Torna-o real.",copy:"Um estúdio e espaço criativo para jovens. Faz música, arte e media. Aprende skate e dança. Desenvolve competências com profissionais e mostra o teu progresso.",cta:"Explorar a Academia ↗",club1Label:"01 / MÚSICA E ÁUDIO",club1Title:"Encontra o teu som.",club1Copy:"Escreve, atua e grava. Leva contigo algo que é teu.",club2Label:"02 / ARTE E MEDIA",club2Title:"Cria algo de que te orgulhes.",club2Copy:"Fotografa, pinta, desenha e mostra o teu trabalho.",club3Label:"03 / MOVIMENTO",club3Title:"Move-te. Aprende. Conquista.",club3Copy:"Encontra o equilíbrio no skate e o ritmo na dança.",footTitle:"CONQUISTA. MOSTRA.",footCopy:"Descobrir → Desenvolver → Conquistar → Liderar. Ganha distintivos ao evoluir.",footLink:"Ver os distintivos ↗"},
  de: {eyebrow:"THE HUB ACADEMY · ZENTRUM LOULÉ",title:"Finde deinen Weg. Mach etwas daraus.",copy:"Ein echtes Studio und kreativer Ort für junge Menschen. Musik, Kunst, Medien, Skate und Tanz mit erfahrenen Profis entdecken und Fortschritte sichtbar machen.",cta:"Academy entdecken ↗",club1Label:"01 / MUSIK & AUDIO",club1Title:"Finde deinen Sound.",club1Copy:"Schreiben, auftreten, aufnehmen. Nimm etwas Eigenes mit.",club2Label:"02 / KUNST & MEDIEN",club2Title:"Mach etwas, auf das du stolz bist.",club2Copy:"Fotografiere, male, gestalte und zeige deine Arbeit.",club3Label:"03 / BEWEGUNG",club3Title:"Beweg dich. Lerne. Schaff es.",club3Copy:"Finde Balance auf dem Board und Rhythmus beim Tanzen.",footTitle:"VERDIENEN. TRAGEN.",footCopy:"Entdecken → Entwickeln → Erreichen → Anleiten. Sammle Patches für deinen Fortschritt.",footLink:"Patch-System ansehen ↗"},
  fr: {eyebrow:"THE HUB ACADEMY · CENTRE DE LOULÉ",title:"Trouve ta voie. Donne-lui vie.",copy:"Un véritable studio et un lieu créatif pour les jeunes. Musique, art, médias, skate et danse avec des professionnels, et des progrès à porter avec fierté.",cta:"Découvrir l'Académie ↗",club1Label:"01 / MUSIQUE & AUDIO",club1Title:"Trouve ton son.",club1Copy:"Écris, joue et enregistre. Repars avec une création à toi.",club2Label:"02 / ART & MÉDIAS",club2Title:"Crée quelque chose dont tu es fier.",club2Copy:"Photographie, peins, imagine et montre ton travail.",club3Label:"03 / MOUVEMENT",club3Title:"Bouge. Essaie. Réussis.",club3Copy:"Trouve ton équilibre sur la planche et ton rythme en danse.",footTitle:"GAGNE-LE. PORTE-LE.",footCopy:"Découvrir → Progresser → Réussir → Guider. Collectionne des écussons en avançant.",footLink:"Voir les écussons ↗"}
};
let currentLanguage = localStorage.getItem("sb-language") || (navigator.language.startsWith("pt") ? "pt" : navigator.language.startsWith("de") ? "de" : navigator.language.startsWith("fr") ? "fr" : "en");

function getText(key){if(key.startsWith("academyHome."))return academyHomeTranslations[currentLanguage]?.[key.split(".")[1]] || academyHomeTranslations.en[key.split(".")[1]] || key;return key.split(".").reduce((value,part)=>value?.[part],translations[currentLanguage]) || key}
function applyLanguage(lang){
  currentLanguage=translations[lang]?lang:"en";localStorage.setItem("sb-language",currentLanguage);document.documentElement.lang=currentLanguage;
  document.querySelectorAll("[data-i18n]").forEach(el=>{const value=getText(el.dataset.i18n);if(value)el.textContent=value});
  document.querySelectorAll(".lang").forEach(btn=>{const active=btn.dataset.lang===currentLanguage;btn.classList.toggle("active",active);btn.setAttribute("aria-pressed",String(active))});
  renderServices();
}

function renderServices(selected){
  const select=document.querySelector("#service");if(!select)return;
  const pageGroup=document.body.dataset.servicePage; const available=pageGroup?sessions.filter(item=>item.group===pageGroup):sessions.filter(item=>!item.fullPayment);
  const prior=selected||select.value||document.body.dataset.defaultService||available[0].id;
  select.innerHTML=available.map(item=>`<option value="${item.id}">${item.names[currentLanguage]} — €${item.price}</option>`).join("");
  select.value=available.some(item=>item.id===prior)?prior:available[0].id;updateTotals();
}

function selectedSession(){return sessions.find(item=>item.id===document.querySelector("#service").value)||sessions[0]}
function updateTotals(){const item=selectedSession();document.querySelector("#session-total").textContent=`€${item.price}`;document.querySelector("#deposit-total").textContent=`€${item.deposit}`;const dateField=document.querySelector("#date")?.closest(".field"),timeField=document.querySelector("#time")?.closest(".field");if(dateField)dateField.hidden=!!item.noSlot;if(timeField)timeField.hidden=!!item.noSlot;if(document.querySelector("#date"))document.querySelector("#date").required=!item.noSlot;if(document.querySelector("#time"))document.querySelector("#time").required=!item.noSlot;const dueLabel=document.querySelector("#deposit-total")?.previousElementSibling;if(dueLabel)dueLabel.textContent=item.fullPayment?(currentLanguage==="pt"?"Pagamento total":currentLanguage==="fr"?"Paiement intégral":"Pay in full"):getText("form.due");if(!item.noSlot&&document.querySelector("#date")?.value)loadAvailability()}
function localSlots(date,item){if(item.noSlot)return[];const day=new Date(`${date}T12:00:00`).getDay();if(item.partySlots)return["10:00","15:00"];if(item.fullDay||item.halfDay)return day>=1&&day<=5?["10:00"]:[];if(day===6)return item.hours<=2?["16:00"]:[];if(day===0)return item.hours<=4?["10:00"]:[];return ["10:00","13:00","16:00"]}

async function loadAvailability(){
  const date=document.querySelector("#date")?.value,time=document.querySelector("#time"),item=selectedSession();if(!date||!time)return;
  time.disabled=true;time.innerHTML=`<option>${getText("form.loading")}</option>`;
  let slots=localSlots(date,item);
  try{const response=await fetch(`/api/availability?date=${encodeURIComponent(date)}&service=${encodeURIComponent(item.id)}`);if(response.ok){const data=await response.json();if(Array.isArray(data.slots))slots=data.slots}}catch(error){}
  time.innerHTML=slots.length?`<option value="">—</option>${slots.map(slot=>`<option value="${slot}">${slot}</option>`).join("")}`:`<option value="">${getText("form.none")}</option>`;time.disabled=!slots.length;
}

document.querySelectorAll(".lang").forEach(btn=>btn.addEventListener("click",()=>applyLanguage(btn.dataset.lang)));
document.querySelector(".menu-toggle").addEventListener("click",event=>{const nav=document.querySelector("#site-nav"),open=nav.classList.toggle("open");event.currentTarget.setAttribute("aria-expanded",String(open))});
document.querySelectorAll(".site-nav a").forEach(link=>link.addEventListener("click",()=>{document.querySelector("#site-nav").classList.remove("open");document.querySelector(".menu-toggle").setAttribute("aria-expanded","false")}));
document.querySelectorAll("[data-service]").forEach(link=>link.addEventListener("click",()=>renderServices(link.dataset.service)));
document.querySelector("#service").addEventListener("change",updateTotals);
if(document.querySelector("#date")){document.querySelector("#date").min=new Date().toISOString().slice(0,10);document.querySelector("#date").addEventListener("change",loadAvailability);}
document.querySelector("#booking-form").addEventListener("submit",async event=>{
  event.preventDefault();const form=event.currentTarget,status=document.querySelector("#form-status");
  if(!form.reportValidity()){status.textContent=getText("form.invalid");return}
  const button=form.querySelector("button[type=submit]");button.disabled=true;status.textContent=getText("form.loading");
  const payload=Object.fromEntries(new FormData(form));payload.language=currentLanguage;
  try{const response=await fetch("/api/create-checkout",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.error||"Unavailable");if(data.url)window.location.href=data.url;else throw new Error("Unavailable")}catch(error){status.textContent=getText("form.error");button.disabled=false}
});
document.querySelector("#year").textContent=new Date().getFullYear();
applyLanguage(currentLanguage);
