const $ = s => document.querySelector(s);
const money = n => new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR'}).format(n/100);
let basket = [], quote = null, revision = 0, busy = false, next = 0;
try { const saved=JSON.parse(localStorage.getItem('sb-shop-basket') || '[]'); if(Array.isArray(saved)) basket=saved.filter(i=>Number.isSafeInteger(i.id)&&Number.isInteger(i.quantity)&&i.quantity>0&&i.quantity<=10&&typeof i.name==='string'&&Number.isSafeInteger(i.price)).slice(0,15); } catch {}
const el = (tag,text,cls) => {const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
async function api(action,body,params='') { const r=await fetch(`/api/shop?action=${action}${params}`,{method:body?'POST':'GET',headers:body?{'content-type':'application/json'}:{},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(d.error||'Please try again.');return d; }
function message(value,error=false){$('#basket-message').textContent=value;$('#basket-message').classList.toggle('shop-error',error);}
function invalidate(){revision++;quote=null;$('#quote').hidden=true;}
function save(){try{localStorage.setItem('sb-shop-basket',JSON.stringify(basket));}catch{}invalidate();renderBasket();}
function renderBasket(){
 const root=$('#basket-items');root.replaceChildren();$('#basket-count').textContent=basket.reduce((n,i)=>n+i.quantity,0);
 if(!basket.length)root.append(el('p','Your basket is empty. Choose something from the collection.'));
 for(const item of basket){const row=el('div',undefined,'shop-line');row.append(el('p',item.name));const controls=el('div',undefined,'shop-line-actions');
 for(const delta of [-1,1]){const b=el('button',delta===1?'+':'−');b.type='button';b.setAttribute('aria-label',`${delta===1?'Increase':'Decrease'} quantity of ${item.name}`);b.onclick=()=>{if(busy)return;item.quantity+=delta;if(item.quantity>10)item.quantity=10;if(item.quantity<1)basket=basket.filter(i=>i!==item);save();};controls.append(b);if(delta===-1)controls.append(el('span',String(item.quantity)));}
 const remove=el('button','Remove','remove');remove.type='button';remove.onclick=()=>{if(busy)return;basket=basket.filter(i=>i!==item);save();};controls.append(remove);row.append(controls,el('p',money(item.price*item.quantity)));root.append(row);}
 $('#basket-subtotal').textContent=basket.length?`Items: ${money(basket.reduce((n,i)=>n+i.price*i.quantity,0))}`:'';$('#quote-button').disabled=busy||!basket.length;
}
async function loadProducts(){const button=$('#load-more');button.disabled=true;try{const data=await api('products',null,`&offset=${next}`);for(const p of data.products){const card=el('article',undefined,'shop-card');if(p.image){const img=el('img');img.src=p.image;img.alt=p.name;img.loading='lazy';img.width=500;img.height=500;card.append(img);}const body=el('div',undefined,'shop-card-body');body.append(el('h3',p.name));const choose=el('button','Choose options','shop-button secondary');body.append(choose);choose.onclick=async()=>{choose.disabled=true;choose.textContent='Loading…';try{const detail=await api('product',null,`&id=${p.id}`);if(!detail.variants.length){choose.textContent='Currently unavailable';return;}choose.remove();const label=el('label','Size / colour / format');const select=el('select');select.append(new Option('Choose an option',''));for(const v of detail.variants)select.append(new Option(`${[v.color,v.size].filter(Boolean).join(" / ") || v.name} — ${money(v.price)}`,v.id));label.append(select);const price=el('p','','variant-price');const add=el('button','Add to basket','shop-button');add.disabled=true;select.onchange=()=>{const v=detail.variants.find(v=>String(v.id)===select.value);add.disabled=!v;price.textContent=v?money(v.price):'';if(v?.image)card.querySelector('img')?.setAttribute('src',v.image);};add.onclick=()=>{if(busy)return;const v=detail.variants.find(v=>String(v.id)===select.value);if(!v)return;const existing=basket.find(i=>i.id===v.id);if(existing&&existing.quantity>=10){message('For more than 10 of one item, please contact us.',true);return;}if(!existing&&basket.length>=15){message('Please contact us for larger orders.',true);return;}if(existing)existing.quantity++;else basket.push({...v,quantity:1});save();message(`${v.name} added to your basket.`);};body.append(label,price,add);}catch(e){choose.disabled=false;choose.textContent='Retry options';message(e.message,true);}};card.append(body);$('#products').append(card);}next=data.next;button.hidden=next===null;$('#catalog-message').textContent=$('#products').children.length?'':'The collection is being prepared. Please check back soon.';
 if($('#country').options.length<=1){const display=new Intl.DisplayNames(['en'],{type:'region'});$('#country').replaceChildren();for(const code of data.countries)$('#country').append(new Option(display.of(code),code));$('#country').value=data.countries.includes('PT')?'PT':data.countries[0];}
 }catch(e){$('#catalog-message').textContent='The collection is temporarily unavailable. Please try again shortly or contact bookings@soundbunker.pt.';button.hidden=false;button.textContent='Retry loading';}finally{button.disabled=false;}}
$('#load-more').onclick=loadProducts;
$('#delivery-form').addEventListener('input',invalidate);
$('#delivery-form').onsubmit=async event=>{event.preventDefault();if(busy||!basket.length)return;invalidate();const current=revision;busy=true;renderBasket();message('Checking your items and delivery…');try{const data=await api('quote',{items:basket.map(i=>({id:i.id,quantity:i.quantity})),recipient:Object.fromEntries(new FormData(event.target))});if(current!==revision){message('Your details changed. Please calculate delivery again.');return;}quote=data;$('#quote-subtotal').textContent=money(data.subtotal);$('#quote-shipping').textContent=money(data.shipping);$('#quote-total').textContent=money(data.total);$('#quote-delivery').textContent=data.delivery;$('#quote').hidden=false;message('Please review your total and delivery address before paying.');}catch(e){message(e.message,true);}finally{busy=false;renderBasket();}};
$('#pay-button').onclick=async()=>{if(!quote||busy||!$('#delivery-form').reportValidity())return;const selected=quote;busy=true;$('#pay-button').disabled=true;$('#delivery-form').querySelectorAll('input,select,button').forEach(n=>n.disabled=true);message('Opening secure payment…');try{const d=await api('checkout',{id:selected.id,token:selected.token});const dest=new URL(d.url);if(dest.protocol!=='https:'||dest.hostname!=='checkout.stripe.com')throw Error('Payment link unavailable.');location.assign(dest.href);}catch(e){message(e.message,true);busy=false;$('#pay-button').disabled=false;$('#delivery-form').querySelectorAll('input,select,button').forEach(n=>n.disabled=false);renderBasket();}};
renderBasket();loadProducts();
