const translations = {
  en: {
    nav:{studio:"Studio",services:"Services",experiences:"Experiences",education:"Education",partnership:"The Hub",contact:"Contact"},
    common:{book:"Book now",bookSession:"Book a session",viewPrices:"View prices",enquire:"Enquire",learnMore:"Explore service"},
    hero:{eyebrow:"Recording studio · Loulé, Algarve",title:"Make something worth hearing.",copy:"Professional recording, production, mixing, voiceover and creative experiences inside The Hub Culture.",explore:"Explore the studio",meta1:"25+ years' experience",meta2:"Release-ready sound",meta3:"Prices include VAT"},
    intro:{eyebrow:"Built for artists",title:"A serious studio without the attitude.",copy:"SoundBunker Algarve brings more than 25 years of recording, production, mixing and mastering experience to central Loulé. Come with a finished track, a rough idea or no experience at all. We will meet you where you are and help you make the work stronger.",prices:"View studio prices"},
    services:{eyebrow:"SoundBunker services",title:"Everything your project needs.",copy:"Record, produce, finish and present your work under one roof.",recording:{title:"Recording & engineering",copy:"Vocals, instruments and complete sessions with an experienced engineer."},production:{title:"Music production",copy:"From the first idea to a bespoke, release-ready record."},mix:{title:"Mixing & mastering",copy:"Detailed, powerful mixes and masters that translate everywhere."},voice:{title:"Remote voiceover",copy:"Broadcast-quality sessions for agencies, brands and talent worldwide."},photo:{title:"Photography",copy:"Portraits, branding, family sessions and content created in the studio."},podcast:{title:"Podcast production",copy:"Professional recording, editing and finishing, including work with Portugal Diaries Podcast."}},
    pricing:{eyebrow:"Clear studio pricing",title:"Choose the time you need.",vat:"All displayed prices include 23% VAT.",engineer:"Recording with engineer",best:"Most popular",hire:"Studio hire",noEngineer:"Without engineer",hours:"hours",day:"Full day",bookHire:"Book studio hire",depositTitle:"Secure your session with €100.",depositCopy:"The VAT-inclusive deposit is paid when booking and the remaining balance is due on the session day."},
    record:{eyebrow:"Create your own original record",title:"Your idea. Your sound. Your release.",copy:"Two focused three-hour sessions to create a bespoke instrumental, record and develop your vocals, then professionally mix and master the finished song.",item1:"Original bespoke production",item2:"Lead vocals, harmonies, layers and effects",item3:"Professional mix and master",item4:"Exclusive rights to release your song",standard:"Standard payment plan",vat:"VAT included",pay1:"Booking deposit",pay2:"Session one",pay3:"Session two",pay4:"On completion",upfront:"Pay upfront and save €50",cta:"Create your record"},
    experience:{eyebrow:"Studio experiences",title:"Step behind the mic.",copy:"Record up to five songs, enjoy a professional photoshoot and take home finished music and photographs.",solo:"Solo",duet:"Duet",family:"Family",one:"One person",two:"Two people",four:"Up to four people",parties:"Birthday, hen and stag parties",partyCopy:"Private group studio experiences for a minimum of ten guests.",birthday:"Birthday from",henstag:"Hen / stag from"},
    market:{eyebrow:"Saturday Market Day · 10:00–14:00",title:"Walk in. Have a go.",copy:"No booking and no big commitment. Drop in while you are visiting Loulé Market for a short recording, a quick photoshoot or both.",mic:"Mic Drop",photo:"Photo Pop-In",combo:"Mic + Pics",vat:"Solo · duet · family. VAT included."},
    education:{eyebrow:"Education & enrichment",title:"After-School Creativity Club",copy:"A bilingual English and Portuguese club where young people make friends, explore creative disciplines and develop the skills that connect with them most.",ages:"Ages 6–16 · 16:30–18:30",explore:"Explore. Discover. Develop.",d1:"Recording & vocals",d2:"Music production",d3:"Mixing & mastering",d4:"Photography",d5:"DJ skills",d6:"Design a T-shirt brand",d7:"Graffiti",d8:"Breakdancing",tue:"Tuesday",wed:"Wednesday",thu:"Thursday",age1:"Ages 6–9",age2:"Ages 10–12",age3:"Ages 13–16",form:"Download registration form",ask:"Ask about a place",trial:"Trial",single:"Single session",weekly:"Weekly",twice:"Twice weekly",term:"12 sessions",month:"/month",priceNote:"Two-hour sessions. VAT included. Creativity Starter Kit €35."},
    photo:{eyebrow:"Photography studio",title:"Professional images, your way.",mini:"Mini · 30 min · 5 images",signature:"Signature · 1 hour · 10 images",premium:"Premium · 90 min · 20 images",branding:"Business branding · 1 hour · 15 images",addons:"Add-ons include extra edits, complete galleries, social reels, behind-the-scenes video and additional studio time."},
    hub:{eyebrow:"SoundBunker × The Hub Culture",title:"One home for sound, art and movement.",copy:"SoundBunker is based inside The Hub Culture, an independent creative community in central Loulé. Together we connect recording, photography, graffiti, skating, dance and youth development in one welcoming space.",location:"Right beside Loulé Municipal Market."},
    reviews:{eyebrow:"Google reviews",title:"Hear it from the people who have recorded here.",copy:"Explore our latest verified reviews or share your SoundBunker experience.",cta:"View Google reviews"},
    booking:{eyebrow:"Online booking",title:"Book your studio time.",copy:"Choose your session, select an available date and secure it with your VAT-inclusive deposit.",rule1:"Weekdays: 10:00, 13:00 or 16:00",rule2:"Saturday: 16:00, two hours only",rule3:"Sunday: 10:00, two or four hours",rule4:"Free move with more than 24 hours' notice",policy:"The deposit is non-refundable for cancellation or changes within 24 hours."},
    form:{service:"Session",date:"Date",time:"Start time",chooseDate:"Choose a date first",name:"Full name",email:"Email",phone:"Phone",nif:"NIF / tax number",notes:"Session notes",terms:"I accept the booking and cancellation terms.",total:"Session total",due:"Due now",pay:"Continue to secure payment",loading:"Checking availability…",none:"No times are available for this date.",error:"Online payment is not connected yet. Please email bookings@soundbunker.pt and we will hold the selected time for you.",invalid:"Please complete all required fields."},
    contact:{eyebrow:"Visit SoundBunker",title:"In the heart of Loulé.",studio:"Studio",directions:"Get directions",bookings:"Bookings",phone:"Telephone number coming soon.",follow:"Follow"}
  },
  pt: {
    nav:{studio:"Estúdio",services:"Serviços",experiences:"Experiências",education:"Educação",partnership:"The Hub",contact:"Contacto"},
    common:{book:"Reservar",bookSession:"Reservar sessão",viewPrices:"Ver preços",enquire:"Pedir informações",learnMore:"Explorar serviço"},
    hero:{eyebrow:"Estúdio de gravação · Loulé, Algarve",title:"Crie algo que merece ser ouvido.",copy:"Gravação profissional, produção, mistura, voz-off e experiências criativas dentro do The Hub Culture.",explore:"Conhecer o estúdio",meta1:"Mais de 25 anos de experiência",meta2:"Som pronto para lançamento",meta3:"Preços com IVA incluído"},
    intro:{eyebrow:"Criado para artistas",title:"Um estúdio profissional, sem atitudes.",copy:"O SoundBunker Algarve traz mais de 25 anos de experiência em gravação, produção, mistura e masterização para o centro de Loulé. Venha com uma faixa acabada, uma ideia inicial ou sem qualquer experiência. Trabalhamos consigo a partir do ponto em que está para tornar o projeto mais forte.",prices:"Ver preços do estúdio"},
    services:{eyebrow:"Serviços SoundBunker",title:"Tudo o que o seu projeto precisa.",copy:"Grave, produza, finalize e apresente o seu trabalho num só espaço.",recording:{title:"Gravação e engenharia",copy:"Vozes, instrumentos e sessões completas com um técnico experiente."},production:{title:"Produção musical",copy:"Da primeira ideia a uma música original pronta para lançamento."},mix:{title:"Mistura e masterização",copy:"Misturas detalhadas e potentes e masters que funcionam em qualquer sistema."},voice:{title:"Voz-off remota",copy:"Sessões com qualidade broadcast para agências, marcas e talentos em qualquer lugar."},photo:{title:"Fotografia",copy:"Retratos, branding, sessões de família e conteúdos criados em estúdio."},podcast:{title:"Produção de podcasts",copy:"Gravação, edição e finalização profissional, incluindo trabalho com o Portugal Diaries Podcast."}},
    pricing:{eyebrow:"Preços simples",title:"Escolha o tempo de que precisa.",vat:"Todos os preços apresentados incluem IVA a 23%.",engineer:"Gravação com técnico",best:"Mais popular",hire:"Aluguer de estúdio",noEngineer:"Sem técnico",hours:"horas",day:"Dia completo",bookHire:"Reservar estúdio",depositTitle:"Garanta a sessão com €100.",depositCopy:"O sinal inclui IVA, é pago na reserva e o saldo restante vence no dia da sessão."},
    record:{eyebrow:"Crie a sua própria música original",title:"A sua ideia. O seu som. O seu lançamento.",copy:"Duas sessões focadas de três horas para criar um instrumental à medida, gravar e desenvolver as vozes e depois misturar e masterizar profissionalmente a música final.",item1:"Produção original à medida",item2:"Voz principal, harmonias, camadas e efeitos",item3:"Mistura e masterização profissionais",item4:"Direitos exclusivos para lançar a música",standard:"Plano de pagamento normal",vat:"IVA incluído",pay1:"Sinal da reserva",pay2:"Primeira sessão",pay3:"Segunda sessão",pay4:"Na conclusão",upfront:"Pague antecipadamente e poupe €50",cta:"Criar a sua música"},
    experience:{eyebrow:"Experiências em estúdio",title:"Entre no estúdio.",copy:"Grave até cinco músicas, faça uma sessão fotográfica profissional e leve música e fotografias finalizadas.",solo:"Solo",duet:"Dueto",family:"Família",one:"Uma pessoa",two:"Duas pessoas",four:"Até quatro pessoas",parties:"Festas de aniversário, despedidas de solteira e de solteiro",partyCopy:"Experiências privadas em estúdio para grupos com um mínimo de dez pessoas.",birthday:"Aniversário desde",henstag:"Despedida desde"},
    market:{eyebrow:"Market Day aos sábados · 10:00–14:00",title:"Entre e experimente.",copy:"Sem reserva nem compromisso. Passe por cá enquanto visita o Mercado de Loulé para uma gravação curta, uma sessão fotográfica rápida ou as duas.",mic:"Mic Drop",photo:"Photo Pop-In",combo:"Mic + Fotos",vat:"Solo · dueto · família. IVA incluído."},
    education:{eyebrow:"Educação e enriquecimento",title:"Clube Criativo Pós-Escolar",copy:"Um clube bilingue em inglês e português onde os jovens fazem amigos, exploram disciplinas criativas e desenvolvem as competências com que mais se identificam.",ages:"Dos 6 aos 16 anos · 16:30–18:30",explore:"Explorar. Descobrir. Desenvolver.",d1:"Gravação e voz",d2:"Produção musical",d3:"Mistura e masterização",d4:"Fotografia",d5:"DJ",d6:"Criar uma marca de T-shirts",d7:"Graffiti",d8:"Breakdance",tue:"Terça-feira",wed:"Quarta-feira",thu:"Quinta-feira",age1:"6–9 anos",age2:"10–12 anos",age3:"13–16 anos",form:"Descarregar ficha de inscrição",ask:"Perguntar sobre vagas",trial:"Aula experimental",single:"Sessão avulsa",weekly:"Semanal",twice:"Duas vezes por semana",term:"12 sessões",month:"/mês",priceNote:"Sessões de duas horas. IVA incluído. Kit Criativo Inicial €35."},
    photo:{eyebrow:"Estúdio fotográfico",title:"Imagens profissionais à sua maneira.",mini:"Mini · 30 min · 5 imagens",signature:"Signature · 1 hora · 10 imagens",premium:"Premium · 90 min · 20 imagens",branding:"Branding empresarial · 1 hora · 15 imagens",addons:"Extras disponíveis: mais edições, galeria completa, reels, vídeo de bastidores e tempo adicional de estúdio."},
    hub:{eyebrow:"SoundBunker × The Hub Culture",title:"Uma casa para som, arte e movimento.",copy:"O SoundBunker está dentro do The Hub Culture, uma comunidade criativa independente no centro de Loulé. Em conjunto, ligamos gravação, fotografia, graffiti, skate, dança e desenvolvimento juvenil num espaço acolhedor.",location:"Mesmo ao lado do Mercado Municipal de Loulé."},
    reviews:{eyebrow:"Avaliações Google",title:"A opinião de quem já gravou connosco.",copy:"Veja as avaliações verificadas mais recentes ou partilhe a sua experiência SoundBunker.",cta:"Ver avaliações Google"},
    booking:{eyebrow:"Reservas online",title:"Reserve tempo de estúdio.",copy:"Escolha a sessão, selecione uma data disponível e garanta-a com o sinal, já com IVA incluído.",rule1:"Dias úteis: 10:00, 13:00 ou 16:00",rule2:"Sábado: 16:00, apenas duas horas",rule3:"Domingo: 10:00, duas ou quatro horas",rule4:"Alteração gratuita com mais de 24 horas de antecedência",policy:"O sinal não é reembolsável em cancelamentos ou alterações com menos de 24 horas."},
    form:{service:"Sessão",date:"Data",time:"Hora de início",chooseDate:"Escolha primeiro uma data",name:"Nome completo",email:"Email",phone:"Telefone",nif:"NIF",notes:"Notas sobre a sessão",terms:"Aceito os termos de reserva e cancelamento.",total:"Total da sessão",due:"A pagar agora",pay:"Continuar para pagamento seguro",loading:"A verificar disponibilidade…",none:"Não existem horários disponíveis nesta data.",error:"O pagamento online ainda não está ligado. Envie um email para bookings@soundbunker.pt e guardaremos o horário selecionado.",invalid:"Preencha todos os campos obrigatórios."},
    contact:{eyebrow:"Visite o SoundBunker",title:"No coração de Loulé.",studio:"Estúdio",directions:"Obter direções",bookings:"Reservas",phone:"Número de telefone disponível em breve.",follow:"Siga-nos"}
  },
  fr: {
    nav:{studio:"Studio",services:"Services",experiences:"Expériences",education:"Éducation",partnership:"The Hub",contact:"Contact"},
    common:{book:"Réserver",bookSession:"Réserver une session",viewPrices:"Voir les tarifs",enquire:"Nous contacter",learnMore:"Découvrir le service"},
    hero:{eyebrow:"Studio d'enregistrement · Loulé, Algarve",title:"Créez quelque chose qui mérite d'être entendu.",copy:"Enregistrement professionnel, production, mixage, voix off et expériences créatives au sein de The Hub Culture.",explore:"Découvrir le studio",meta1:"Plus de 25 ans d'expérience",meta2:"Son prêt à sortir",meta3:"Prix TVA comprise"},
    intro:{eyebrow:"Conçu pour les artistes",title:"Un studio sérieux, sans prétention.",copy:"SoundBunker Algarve apporte plus de 25 ans d'expérience en enregistrement, production, mixage et mastering au centre de Loulé. Venez avec un morceau terminé, une première idée ou sans aucune expérience. Nous partons de votre niveau pour renforcer votre projet.",prices:"Voir les tarifs du studio"},
    services:{eyebrow:"Services SoundBunker",title:"Tout ce dont votre projet a besoin.",copy:"Enregistrez, produisez, finalisez et présentez votre travail sous un même toit.",recording:{title:"Enregistrement & ingénierie",copy:"Voix, instruments et sessions complètes avec un ingénieur expérimenté."},production:{title:"Production musicale",copy:"De la première idée à un titre original prêt à sortir."},mix:{title:"Mixage & mastering",copy:"Des mixages précis et puissants et des masters qui fonctionnent partout."},voice:{title:"Voix off à distance",copy:"Sessions de qualité broadcast pour les agences, marques et talents du monde entier."},photo:{title:"Photographie",copy:"Portraits, image de marque, familles et contenu créés en studio."},podcast:{title:"Production de podcasts",copy:"Enregistrement, montage et finition professionnels, avec notamment Portugal Diaries Podcast."}},
    pricing:{eyebrow:"Tarifs simples",title:"Choisissez le temps nécessaire.",vat:"Tous les prix affichés incluent 23 % de TVA.",engineer:"Enregistrement avec ingénieur",best:"Le plus populaire",hire:"Location du studio",noEngineer:"Sans ingénieur",hours:"heures",day:"Journée complète",bookHire:"Réserver le studio",depositTitle:"Réservez votre session avec 100 €.",depositCopy:"L'acompte, TVA comprise, est payé à la réservation. Le solde est dû le jour de la session."},
    record:{eyebrow:"Créez votre propre titre original",title:"Votre idée. Votre son. Votre sortie.",copy:"Deux sessions ciblées de trois heures pour créer un instrumental sur mesure, enregistrer et développer les voix, puis mixer et masteriser professionnellement le titre final.",item1:"Production originale sur mesure",item2:"Voix principale, harmonies, couches et effets",item3:"Mixage et mastering professionnels",item4:"Droits exclusifs pour sortir votre titre",standard:"Paiement standard",vat:"TVA comprise",pay1:"Acompte de réservation",pay2:"Première session",pay3:"Deuxième session",pay4:"À la fin",upfront:"Payez d'avance et économisez 50 €",cta:"Créer votre titre"},
    experience:{eyebrow:"Expériences studio",title:"Passez derrière le micro.",copy:"Enregistrez jusqu'à cinq chansons, profitez d'une séance photo professionnelle et repartez avec votre musique et vos photos finalisées.",solo:"Solo",duet:"Duo",family:"Famille",one:"Une personne",two:"Deux personnes",four:"Jusqu'à quatre personnes",parties:"Anniversaires, EVJF et EVG",partyCopy:"Expériences privées en studio pour des groupes de dix personnes minimum.",birthday:"Anniversaire dès",henstag:"EVJF / EVG dès"},
    market:{eyebrow:"Market Day le samedi · 10:00–14:00",title:"Entrez et essayez.",copy:"Sans réservation ni gros engagement. Passez pendant votre visite du marché de Loulé pour un court enregistrement, une séance photo rapide ou les deux.",mic:"Mic Drop",photo:"Photo Pop-In",combo:"Mic + Photos",vat:"Solo · duo · famille. TVA comprise."},
    education:{eyebrow:"Éducation & enrichissement",title:"Club Créatif Après l'École",copy:"Un club bilingue anglais-portugais où les jeunes se font des amis, explorent des disciplines créatives et développent les compétences qui leur correspondent le mieux.",ages:"De 6 à 16 ans · 16:30–18:30",explore:"Explorer. Découvrir. Développer.",d1:"Enregistrement & chant",d2:"Production musicale",d3:"Mixage & mastering",d4:"Photographie",d5:"DJ",d6:"Créer une marque de T-shirts",d7:"Graffiti",d8:"Breakdance",tue:"Mardi",wed:"Mercredi",thu:"Jeudi",age1:"6–9 ans",age2:"10–12 ans",age3:"13–16 ans",form:"Télécharger le formulaire",ask:"Demander une place",trial:"Essai",single:"Session unique",weekly:"Chaque semaine",twice:"Deux fois par semaine",term:"12 sessions",month:"/mois",priceNote:"Sessions de deux heures. TVA comprise. Kit Créatif de Départ 35 €."},
    photo:{eyebrow:"Studio photo",title:"Des images professionnelles à votre façon.",mini:"Mini · 30 min · 5 images",signature:"Signature · 1 heure · 10 images",premium:"Premium · 90 min · 20 images",branding:"Image de marque · 1 heure · 15 images",addons:"Options : retouches supplémentaires, galerie complète, reels, vidéo en coulisses et temps de studio supplémentaire."},
    hub:{eyebrow:"SoundBunker × The Hub Culture",title:"Un lieu pour le son, l'art et le mouvement.",copy:"SoundBunker se trouve au sein de The Hub Culture, une communauté créative indépendante au centre de Loulé. Ensemble, nous réunissons enregistrement, photographie, graffiti, skate, danse et développement des jeunes dans un espace accueillant.",location:"Juste à côté du marché municipal de Loulé."},
    reviews:{eyebrow:"Avis Google",title:"Écoutez ceux qui ont déjà enregistré ici.",copy:"Consultez nos derniers avis vérifiés ou partagez votre expérience SoundBunker.",cta:"Voir les avis Google"},
    booking:{eyebrow:"Réservation en ligne",title:"Réservez votre studio.",copy:"Choisissez votre session, sélectionnez une date disponible et confirmez avec votre acompte TVA comprise.",rule1:"En semaine : 10:00, 13:00 ou 16:00",rule2:"Samedi : 16:00, deux heures uniquement",rule3:"Dimanche : 10:00, deux ou quatre heures",rule4:"Déplacement gratuit avec plus de 24 heures de préavis",policy:"L'acompte n'est pas remboursable en cas d'annulation ou de modification dans les 24 heures."},
    form:{service:"Session",date:"Date",time:"Heure de début",chooseDate:"Choisissez d'abord une date",name:"Nom complet",email:"E-mail",phone:"Téléphone",nif:"NIF / numéro fiscal",notes:"Notes sur la session",terms:"J'accepte les conditions de réservation et d'annulation.",total:"Total de la session",due:"À payer maintenant",pay:"Continuer vers le paiement sécurisé",loading:"Vérification des disponibilités…",none:"Aucun horaire n'est disponible à cette date.",error:"Le paiement en ligne n'est pas encore connecté. Écrivez à bookings@soundbunker.pt et nous garderons l'horaire choisi.",invalid:"Veuillez remplir tous les champs obligatoires."},
    contact:{eyebrow:"Visiter SoundBunker",title:"Au cœur de Loulé.",studio:"Studio",directions:"Itinéraire",bookings:"Réservations",phone:"Numéro de téléphone bientôt disponible.",follow:"Suivre"}
  }
};

const sessions = [
  {id:"recording-2h",price:250,deposit:100,hours:2,names:{en:"Recording with engineer · 2 hours",pt:"Gravação com técnico · 2 horas",fr:"Enregistrement avec ingénieur · 2 heures"}},
  {id:"recording-4h",price:450,deposit:100,hours:4,names:{en:"Recording with engineer · 4 hours",pt:"Gravação com técnico · 4 horas",fr:"Enregistrement avec ingénieur · 4 heures"}},
  {id:"recording-day",price:675,deposit:100,hours:7,fullDay:true,names:{en:"Recording with engineer · Full day",pt:"Gravação com técnico · Dia completo",fr:"Enregistrement avec ingénieur · Journée complète"}},
  {id:"hire-2h",price:100,deposit:100,hours:2,names:{en:"Studio hire · 2 hours",pt:"Aluguer de estúdio · 2 horas",fr:"Location du studio · 2 heures"}},
  {id:"hire-4h",price:175,deposit:100,hours:4,names:{en:"Studio hire · 4 hours",pt:"Aluguer de estúdio · 4 horas",fr:"Location du studio · 4 heures"}},
  {id:"hire-day",price:275,deposit:100,hours:7,fullDay:true,names:{en:"Studio hire · Full day",pt:"Aluguer de estúdio · Dia completo",fr:"Location du studio · Journée complète"}}
];

let currentLanguage = localStorage.getItem("sb-language") || (navigator.language.startsWith("pt") ? "pt" : navigator.language.startsWith("fr") ? "fr" : "en");

function getText(key){return key.split(".").reduce((value,part)=>value?.[part],translations[currentLanguage]) || key}
function applyLanguage(lang){
  currentLanguage=translations[lang]?lang:"en";localStorage.setItem("sb-language",currentLanguage);document.documentElement.lang=currentLanguage;
  document.querySelectorAll("[data-i18n]").forEach(el=>{const value=getText(el.dataset.i18n);if(value)el.textContent=value});
  document.querySelectorAll(".lang").forEach(btn=>{const active=btn.dataset.lang===currentLanguage;btn.classList.toggle("active",active);btn.setAttribute("aria-pressed",String(active))});
  renderServices();
}

function renderServices(selected){
  const select=document.querySelector("#service");if(!select)return;
  const prior=selected||select.value||document.body.dataset.defaultService||sessions[0].id;
  select.innerHTML=sessions.map(item=>`<option value="${item.id}">${item.names[currentLanguage]} — €${item.price}</option>`).join("");
  select.value=sessions.some(item=>item.id===prior)?prior:sessions[0].id;updateTotals();
}

function selectedSession(){return sessions.find(item=>item.id===document.querySelector("#service").value)||sessions[0]}
function updateTotals(){const item=selectedSession();document.querySelector("#session-total").textContent=`€${item.price}`;document.querySelector("#deposit-total").textContent=`€${item.deposit}`;if(document.querySelector("#date").value)loadAvailability()}
function localSlots(date,item){const day=new Date(`${date}T12:00:00`).getDay();if(item.fullDay)return day>=1&&day<=5?["10:00"]:[];if(day===6)return item.hours===2?["16:00"]:[];if(day===0)return item.hours===2||item.hours===4?["10:00"]:[];return ["10:00","13:00","16:00"]}

async function loadAvailability(){
  const date=document.querySelector("#date").value,time=document.querySelector("#time"),item=selectedSession();if(!date)return;
  time.disabled=true;time.innerHTML=`<option>${getText("form.loading")}</option>`;
  let slots=localSlots(date,item);
  try{const response=await fetch(`/api/availability?date=${encodeURIComponent(date)}&service=${encodeURIComponent(item.id)}`);if(response.ok){const data=await response.json();if(Array.isArray(data.slots))slots=data.slots}}catch(error){}
  time.innerHTML=slots.length?`<option value="">—</option>${slots.map(slot=>`<option value="${slot}">${slot}</option>`).join("")}`:`<option value="">${getText("form.none")}</option>`;time.disabled=!slots.length;
}

document.querySelectorAll(".lang").forEach(btn=>btn.addEventListener("click",()=>applyLanguage(btn.dataset.lang)));
document.querySelector(".menu-toggle").addEventListener("click",event=>{const nav=document.querySelector("#site-nav"),open=nav.classList.toggle("open");event.currentTarget.setAttribute("aria-expanded",String(open))});
document.querySelectorAll(".site-nav a").forEach(link=>link.addEventListener("click",()=>{document.querySelector("#site-nav").classList.remove("open");document.querySelector(".menu-toggle").setAttribute("aria-expanded","false")}));
document.querySelectorAll("[data-service]").forEach(link=>link.addEventListener("click",()=>renderServices(link.dataset.service)));
document.querySelector("#service").addEventListener("change",updateTotals);
document.querySelector("#date").min=new Date().toISOString().slice(0,10);
document.querySelector("#date").addEventListener("change",loadAvailability);
document.querySelector("#booking-form").addEventListener("submit",async event=>{
  event.preventDefault();const form=event.currentTarget,status=document.querySelector("#form-status");
  if(!form.reportValidity()){status.textContent=getText("form.invalid");return}
  const button=form.querySelector("button[type=submit]");button.disabled=true;status.textContent=getText("form.loading");
  const payload=Object.fromEntries(new FormData(form));payload.language=currentLanguage;
  try{const response=await fetch("/api/create-checkout",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.error||"Unavailable");if(data.url)window.location.href=data.url;else throw new Error("Unavailable")}catch(error){status.textContent=getText("form.error");button.disabled=false}
});
document.querySelector("#year").textContent=new Date().getFullYear();
applyLanguage(currentLanguage);
